language: java

sudo: false

script: "mvn package --settings travis/settings.xml"

jdk:
  - oraclejdk7

env:
  global:
  - secure: "RfUZoJzEIankriAhQzyZxrLC6jAA696WRianWFJrXhlpIdbyuEbLLoMk98+N7GdGvSOON2gLHD6lBUXDJag1l6zI9up4ExiDfAUip78cYEUzXxHc5uLvWfOfiecmu7Ql1um/LrKM0/jZTt7jFRU2bpZ9y6nKx/tRuXXZGZIxOrJlpW4Je+eIHLQUs7OZuBj9q1UJg5JuscNbJNyVPq2ezEdo5CVPPaF98h87fpyVHrkp0uEJAmTC2RcZowzo2swA9L6Cd+bJFnQA1hYCrynic/58gCfKDzzf8CYj6iGbS4MV6Z1w3PXzZraBW8QyJw9T9hoftVZO/azOp5lXEinn50Nfm/WuR+mbzggsWfrEeez8mOLAwjrWptsqJWN2pGR+DZ2CRlivE23mao8oM6T8v+LmxbrL4b66BtTpamA8CCLAFDi2O2gsqmycEHvfRojZHQ8wX9q67LgoCVbeGXbjM7hkzQ/44yyeHiTUZTvnXoGufgJZXeaxbV65Fg8e39o2db6Rt2xp9vrq5+ea/CY3viMJbm6uzhyURXe2Fn48neaSHTODv6jSOiw8Zg2X27THBp3P+aB53VsvN5rHxz6gzA+46vn/n7gLIpi5Ps/MuVTtFGTGTcNIw892Sa5BgLg2wFVZJvTUC6BrDs9UpTpZT8bNk4+unIO/RRIK1lyGXh8="
  - secure: "kkcmJ1aeM4hnmLVUmr0zSK3tagCt6Ba/v3z/FRRfqYILYiG+hjDqowaxBbOuTULU8xPhRnCU5dE35e2IFIHULuC7EmrtvViDzi7IUOggiUjQr+vNQKIVWbiuDhc0BpMbFWpO1HqHvF/fcu37hzy8Ao5jzTxtE+Nn8QHaIEj4fCOIalczjMFXMtJV+xZJgbqx01B4bB1Tx7fyDUB16tbFBQdqSGg3Apk283+RuD1dkUTcxUM4EjcN847SY0FnVV047D+jzfhu5yZkVsqVUk4NK/m+BP1mmrOibWfBJ+43gC3OOkfRAvhakYdUZORizGHXB9m9E5v1WRlq/xWClMMrOxYcVmFoMJEIEe81vL8lKFG4GTkn3roiAdswvhq2XCwcRCSjloq5HXmdOnDtyoLLdYYcTW9mpcZPRCCcgGMag1lsR4+DiGLzMSa7typTHjM2c2KlpS0nLGhBGAlF8gR3e0QpvcmUMONvmuzx0Ww+6DcjPFswOitF/SXLSP06TVoNDHZzEMv+wMtqWHJmLKi987fqGUGe9pcgXzYrR+z6bkgI2RXECfkRB2xZuNpkM/cH41EjTSAjmrKdULFhJkSSMsCsK55qaP7CEHY6kZctSCO7ckgwZh+buT5gJDTHCx/z8ccjaAAGNAa8i7l46lMsYxbkojIhuK8hvHD5xvqZoAM="

after_success:
- chmod -R 777 ./travis/deploy-to-sonatype.sh
- ./travis/deploy-to-sonatype.sh
